### ISSUE TITLE
Color bleeding

### ISSUE THREAD

**Issue by Hefeweizen** [aaossa/git-activity#3]
Using a default Ubuntu 22.04 machine:
![Screen Shot 2022-05-28 at 10 32 29 AM](https://user-images.githubusercontent.com/3291490/170836515-072ba6bc-4152-4823-9541-945270f58ff8.png)

**Comment by aaossa** [comment]
Hi, thank your for reporting this. I'm not sure about what could have happened. I thought, ANSI escape codes where portable. Any ideas on your end? I'll try to research a bit about this

**Comment by tapresle** [comment]
It seems to happen when using 24-bit ANSI color codes on terminals that don’t support it. I replicated on my Mac. However the colors work on a different terminal like one included with VS Code or IntelliJ

**Comment by aaossa** [comment]
Great @tapresle , thank you for the information and the linked PR. @Hefeweizen , can you please confirm if #4 solves the issue for you?

**Comment by aaossa** [comment]
A single command to check if the proposed change displays the expected color in your console @Hefeweizen 

```bash
printf "\x1b[38;2;14;250;41mCurrent \x1b[38;5;40mProposed\e[m\n"
```

This is the output I get:

![image](https://user-images.githubusercontent.com/10425834/172208072-a9eedcc1-ef99-46fc-9636-6e9c30e5c8b4.png)

I'm expecting that you see the bleeding around "Current" but the correct output around "Proposed"
